# Generated by Django 5.2.10 on 2026-01-13 04:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(auto_now_add=True)),
                ('trade_date', models.DateField(db_index=True)),
                ('review_type', models.CharField(choices=[('DAILY', '日复盘'), ('WEEKLY', '周复盘'), ('MONTHLY', '月复盘')], db_index=True, max_length=10)),
                ('market_phase', models.CharField(choices=[('UPTREND', '上升趋势'), ('DOWNTREND', '下降趋势'), ('CONSOLIDATION', '盘整'), ('REVERSAL', '反转')], db_index=True, max_length=15)),
                ('key_levels', models.JSONField(default=dict, help_text='关键价位 {"support": [], "resistance": []}')),
                ('analysis_notes', models.TextField(blank=True)),
                ('screenshots', models.JSONField(default=list, help_text='截图路径列表')),
                ('tags', models.CharField(blank=True, help_text='标签，逗号分隔', max_length=200)),
                ('rating', models.IntegerField(blank=True, help_text='评分 1-5星', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market_data.instrument')),
            ],
            options={
                'db_table': 'review_record',
                'ordering': ['-trade_date'],
            },
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True)),
                ('trade_type', models.CharField(choices=[('LONG', '做多'), ('SHORT', '做空')], db_index=True, max_length=5)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('entry_reason', models.TextField(blank=True)),
                ('exit_reason', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market_data.instrument')),
                ('review_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='review.reviewrecord')),
            ],
            options={
                'db_table': 'review_trade_log',
                'ordering': ['-trade_date'],
            },
        ),
        migrations.AddIndex(
            model_name='reviewrecord',
            index=models.Index(fields=['instrument', 'trade_date'], name='review_reco_instrum_91c0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrecord',
            index=models.Index(fields=['review_type', 'trade_date'], name='review_reco_review__bc97e9_idx'),
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['instrument', 'trade_date'], name='review_trad_instrum_2029c9_idx'),
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['trade_type', 'trade_date'], name='review_trad_trade_t_b643a2_idx'),
        ),
    ]
