# Generated by Django 5.2.10 on 2026-01-13 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('MA', '移动平均线'), ('EMA', '指数移动平均'), ('MACD', 'MACD'), ('RSI', 'RSI'), ('KDJ', 'KDJ'), ('BOLL', '布林带')], db_index=True, max_length=10)),
                ('indicator_data', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('kline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='market_data.kline')),
            ],
            options={
                'db_table': 'technical_indicator',
                'indexes': [models.Index(fields=['kline', 'indicator_type'], name='technical_i_kline_i_0dc969_idx')],
                'unique_together': {('kline', 'indicator_type')},
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('HEAD_SHOULDER', '头肩顶'), ('INV_HEAD_SHOULDER', '头肩底'), ('DOUBLE_TOP', '双顶'), ('DOUBLE_BOTTOM', '双底'), ('UPTREND', '上升趋势'), ('DOWNTREND', '下降趋势'), ('CONSOLIDATION', '盘整')], db_index=True, max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('confidence', models.IntegerField(help_text='置信度 0-100')),
                ('key_points', models.JSONField(default=dict, help_text='关键点位数据')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='market_data.instrument')),
            ],
            options={
                'db_table': 'technical_pattern',
                'ordering': ['-end_date'],
                'indexes': [models.Index(fields=['instrument', 'pattern_type', 'end_date'], name='technical_p_instrum_b879f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('SUPPORT', '支撑位'), ('RESISTANCE', '阻力位')], db_index=True, max_length=10)),
                ('price_level', models.DecimalField(decimal_places=4, max_digits=12)),
                ('strength', models.IntegerField(help_text='强度 1-5')),
                ('identified_date', models.DateField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('touch_count', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_resistance', to='market_data.instrument')),
            ],
            options={
                'db_table': 'technical_support_resistance',
                'ordering': ['-identified_date', 'price_level'],
                'indexes': [models.Index(fields=['instrument', 'is_active', 'level_type'], name='technical_s_instrum_edc37b_idx')],
            },
        ),
    ]
