# Generated by Django 5.2.10 on 2026-01-13 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('market_type', models.CharField(choices=[('STOCK', '股票'), ('FUTURES', '期货')], db_index=True, max_length=10)),
                ('exchange', models.CharField(choices=[('SSE', '上海证券交易所'), ('SZSE', '深圳证券交易所'), ('CFFEX', '中国金融期货交易所'), ('SHFE', '上海期货交易所'), ('DCE', '大连商品交易所'), ('CZCE', '郑州商品交易所')], max_length=10)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('delisting_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_instrument',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='KLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1m', '1分钟'), ('5m', '5分钟'), ('15m', '15分钟'), ('30m', '30分钟'), ('1h', '1小时'), ('1d', '日线'), ('1w', '周线'), ('1M', '月线')], db_index=True, max_length=5)),
                ('trade_date', models.DateField(db_index=True)),
                ('trade_time', models.TimeField(blank=True, null=True)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('open_interest', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klines', to='market_data.instrument')),
            ],
            options={
                'db_table': 'market_kline',
                'ordering': ['-trade_date', '-trade_time'],
                'indexes': [models.Index(fields=['instrument', 'period', 'trade_date'], name='market_klin_instrum_61173a_idx')],
                'unique_together': {('instrument', 'period', 'trade_date', 'trade_time')},
            },
        ),
    ]
